const products = [
    {
        id: 1,
        name: "Oud Elite",
        category: "Women",
        price: 125.00,
        prices: { "10ML": 399, "20ML": 799, "30ML": 1199, "50ML": 1499 },
        image: "product pictures/1.jpeg",
        description: "A profound and luxurious fragrance featuring rich oud wood, spiced saffron, and dark amber for a bold presence.",
        ingredients: "Alcohol Denat, Parfum (Fragrance), Aqua (Water), Linalool, Limonene, Citronellol.",
        tags: { gender: "For her", type: "Designer", concentration: "Eau de parfum" },
        fragrance_notes: ["Oud", "Saffron", "Amber", "Patchouli"],
        seasons: ["Fall", "Winter"],
        occasions: ["Evening", "Formal", "Signature"]
    },
    {
        id: 2,
        name: "Midnight Rose",
        category: "Women",
        price: 95.00,
        prices: { "10ML": 399, "20ML": 799, "30ML": 1199, "50ML": 1499 },
        image: "product pictures/2.jpeg",
        description: "An intoxicating blend of dark blooming roses, blackcurrant, and a touch of vanilla for an unforgettable evening.",
        ingredients: "Alcohol Denat, Parfum (Fragrance), Aqua (Water), Geraniol, Benzyl Salicylate.",
        tags: { gender: "For her", type: "Niche", concentration: "Eau de parfum" },
        fragrance_notes: ["Rose", "Blackcurrant", "Vanilla"],
        seasons: ["Fall", "Winter", "Spring"],
        occasions: ["Evening", "Date Night"]
    },
    {
        id: 3,
        name: "Amber Noir",
        category: "Unisex",
        price: 110.00,
        prices: { "10ML": 399, "20ML": 799, "30ML": 1199, "50ML": 1499 },
        image: "product pictures/3.jpg",
        description: "A warm, enveloping scent of smoked amber, patchouli, and cedarwood perfect for any occasion.",
        ingredients: "Alcohol Denat, Parfum (Fragrance), Aqua (Water), Coumarin, Alpha-Isomethyl Ionone.",
        tags: { gender: "Unisex", type: "Niche", concentration: "Extrait de parfum" },
        fragrance_notes: ["Amber", "Patchouli", "Cedarwood", "Smoke"],
        seasons: ["Fall", "Winter"],
        occasions: ["Signature", "Evening"]
    },
    {
        id: 4,
        name: "Velvet Musk",
        category: "Women",
        price: 85.00,
        prices: { "10ML": 399, "20ML": 799, "30ML": 1199, "50ML": 1499 },
        image: "product pictures/4.jpg",
        description: "Soft, clean, and intimately sensual. A pure musk profile elevated with hints of white florals and cashmere woods.",
        ingredients: "Alcohol Denat, Parfum (Fragrance), Aqua (Water), Hydroxycitronellal, Hexyl Cinnamal.",
        tags: { gender: "For her", type: "Designer", concentration: "Eau de toilette" },
        fragrance_notes: ["Musk", "White Florals", "Cashmere Wood"],
        seasons: ["Spring", "Summer", "Fall"],
        occasions: ["Daytime", "Office", "Casual"]
    },
    {
        id: 5,
        name: "Sandalwood Reserve",
        category: "Women",
        price: 130.00,
        prices: { "10ML": 399, "20ML": 799, "30ML": 1199, "50ML": 1499 },
        image: "product pictures/5.jpg",
        description: "A refined woody aromatic masterpiece, showcasing creamy sandalwood, vetiver, and a whisper of cardamom.",
        ingredients: "Alcohol Denat, Parfum (Fragrance), Aqua (Water), Farnesol, Citral.",
        tags: { gender: "For her", type: "Niche", concentration: "Eau de parfum" },
        fragrance_notes: ["Sandalwood", "Vetiver", "Cardamom"],
        seasons: ["Fall", "Spring"],
        occasions: ["Formal", "Office", "Signature"]
    },
    {
        id: 6,
        name: "Jasmine Bloom",
        category: "Women",
        price: 90.00,
        prices: { "10ML": 399, "20ML": 799, "30ML": 1199, "50ML": 1499 },
        image: "product pictures/6.jpg",
        description: "A radiant and fresh floral bouquet bursting with night-blooming jasmine, bergamot, and sweet neroli.",
        ingredients: "Alcohol Denat, Parfum (Fragrance), Aqua (Water), Benzyl Benzoate, Eugenol.",
        tags: { gender: "For her", type: "Designer", concentration: "Eau de parfum" },
        fragrance_notes: ["Jasmine", "Bergamot", "Neroli"],
        seasons: ["Spring", "Summer"],
        occasions: ["Daytime", "Date Night"]
    },
    {
        id: 7,
        name: "Imperial Oud",
        category: "Men",
        price: 140.00,
        prices: { "10ML": 399, "20ML": 799, "30ML": 1199, "50ML": 1499 },
        image: "product pictures/7.jpg",
        description: "The crown jewel of our collection, featuring aged Cambodian oud blended with spicy notes and precious woods.",
        ingredients: "Alcohol Denat, Parfum (Fragrance), Aqua (Water), Limonene, Linalool, Citral.",
        tags: { gender: "For him", type: "Niche", concentration: "Extrait de parfum" },
        fragrance_notes: ["Cambodian Oud", "Spices", "Precious Woods"],
        seasons: ["Winter", "Fall"],
        occasions: ["Formal", "Signature"]
    }
];
